# NumPy Array Creation

* #### An array allows us to store a collection of multiple values in a single data structure.

* #### The NumPy array is similar to a list, but with added benefits such as being faster and more memory efficient

## Create Array Using Python List

In [6]:
import numpy as np
list1 = [ 1, 2, 3, 4 ]
arr = np.array(list1)
print(arr)

[1 2 3 4]


In [8]:
import numpy as np
arr = np.array([ 5, 6, 7 ])
print(arr)

[5 6 7]


* ### Unlike lists, arrays can only store data of a similar type

## Create an Array Using np.zeros()

#### The np.zeros() function allows us to create an array filled with all zeros

In [27]:
import numpy as np
arr = np.zeros([2,3])
print (arr)

[[0. 0. 0.]
 [0. 0. 0.]]


## Create an array using np.ones()

In [85]:
import numpy as np
arr = np.ones([2,3,2])
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


## Create an Array With np.arange()

In [89]:
import numpy as np
arr_1 = np.arange(5)
print(arr_1)
arr_2 = np.arange(1,12,2)
print(arr_2)

[0 1 2 3 4]
[ 1  3  5  7  9 11]


## Create an Array With np.random.rand()

* #### The np.random.rand() function is used to create an array of random numbers

In [117]:
import numpy as np
array1 = np.random.rand(2)

print(array1)

[0.35246503 0.81022261]


## Create an Array With np.random.randint()

In [112]:
import numpy as np
array1 = np.random.randint(2,7,size=(3,2))

print(array1)

[[6 6]
 [5 2]
 [2 3]]


In [101]:
import numpy as np
array1 = np.random.randint(2,7,size=(3,2))

print(array1)

[[5 5]
 [2 2]
 [3 4]]


## Create an Empty NumPy Array

### np.empty()

In [127]:
import numpy as np
array6 = np.empty(5)

print(array6)

[0.65281968 0.88845356 0.20145511 0.2391631  0.89609954]


* ### In this output array fills some values for empty array , the filled values are arbitrary values it has no significance