# Computation on NumPy arrays

### 1. **Universal Functions (ufuncs)**

**Universal functions** are functions that operate element-wise on arrays. They are optimized to handle large data sets efficiently. Some common ufuncs include mathematical functions, statistical functions, and logical operations.

#### Examples:

In [18]:

import numpy as np

# Arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


sum_result = np.add(a, b)
print(sum_result)

sqrt_result = np.sqrt(a) 
print(sqrt_result)
exp_result = np.exp(a)
print(exp_result)

# Statistical ufuncs
mean_result = np.mean(a)       
std_result = np.std(a)
print(mean_result)
print(std_result) 

# Logical ufuncs
logical_and_result = np.logical_and(a > 1, b < 6)  
print(logical_and_result)

[5 7 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
2.0
0.816496580927726
[False  True False]


### Mean

In [1]:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
print(mean)  


3.0


### 2. **Broadcasting**

**Broadcasting** allows NumPy to perform arithmetic operations on arrays of different shapes by "stretching" the smaller array across the larger array. This is done efficiently without the need for explicit replication of data.

#### Example:

In [23]:
# Arrays with different shapes
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

# Broadcasting
result = a + b  
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


### 3. **Aggregation and Reduction**

**Aggregation functions** reduce the dimensionality of arrays by summarizing data, such as summing, averaging, or finding the maximum value.


#### Examples:

In [30]:
# Arrays
a = np.array([[1, 2, 3], [4, 5, 6]])

# Aggregation functions
sum_all = np.sum(a)               
sum_axis0 = np.sum(a, axis=0)     # Sum of columns
mean_axis1 = np.mean(a, axis=1)    # Mean of rows
max_value = np.max(a)            
min_value = np.min(a)  
print(sum_all)
print(sum_axis0)
print(mean_axis1)
print(max_value)
print(min_value)


21
[5 7 9]
[2. 5.]
6
1


### 4. **Element-wise Operations**

**Element-wise operations** apply a function to each element of an array individually, allowing for efficient computation without explicit loops.




#### Examples:

In [36]:

# Arrays
a = np.array([1, 2, 3])

# Element-wise operations
squared = np.power(a, 2) 
reciprocal = np.reciprocal(a)  
print(squared)
print(reciprocal)

[1 4 9]
[1 0 0]



### 5. **Aggregate Functions on Multidimensional Arrays**

For multidimensional arrays, you can specify the axis along which the aggregation should be performed, allowing for more granular data summarization.





#### Examples:

In [42]:

# 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Sum along different axes
sum_axis0 = np.sum(array_3d, axis=0) 
sum_axis1 = np.sum(array_3d, axis=1)  
sum_axis2 = np.sum(array_3d, axis=2) 
print(sum_axis0)
print(sum_axis1)
print(sum_axis2)

[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]


In [ ]:

### 6. **Advanced Ufuncs**

NumPy also supports more advanced universal functions for specific needs:

- **Trigonometric functions**: `np.sin()`, `np.cos()`, `np.tan()`
- **Hyperbolic functions**: `np.sinh()`, `np.cosh()`, `np.tanh()`
- **Special functions**: `np.gamma()`, `np.log10()`, `np.erf()`





#### Example:

In [49]:

# Trigonometric functions
angles = np.array([0, np.pi/2, np.pi])
sin_values = np.sin(angles)  
print(sin_values)

# Hyperbolic functions
x = np.array([0, 1, 2])
sinh_values = np.sinh(x) 
print(sinh_values)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[0.         1.17520119 3.62686041]


### 7. **Conditional Operations**

**Conditional operations** involve applying conditions to arrays, often with boolean indexing or `np.where()`:


In [55]:

# Arrays
a = np.array([1, 2, 3, 4, 5])

# Conditional selection
filtered = a[a > 2]  
print(filtered)

# Conditional operation with np.where
result = np.where(a > 3, 'Greater', 'Smaller') 
print(result)

[3 4 5]
['Smaller' 'Smaller' 'Smaller' 'Greater' 'Greater']


Universal computation on NumPy arrays involves using **ufuncs** for efficient element-wise operations, leveraging **broadcasting** for operations on arrays of different shapes, performing **aggregation** and **reduction** to summarize data, and applying **conditional operations** for filtering and modifying arrays based on specific criteria. Understanding and utilizing these operations effectively allows you to perform complex computations efficiently and concisely.