In [ ]:
import numpy as np

**Creation of 1D Array**

In [10]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


**Creation of 2D Array**

In [14]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


**Creation of 3D Array**

In [17]:
c = np.array([[[1,2,3]],
              
              [[4,5,6]],
              
              [[7,8,9]]])
print(c)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


**Shape**

In [20]:
print(c.shape)

(3, 1, 3)


**Dimension**

In [23]:
print(a.ndim)

1


## Common Functions

**zeros**

In [27]:
print(np.zeros([3,2,5]))

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


**ones**

In [30]:
print(np.ones([4,2]))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**Full Numpy Array**

In [33]:
print(np.full([3,2],1))

[[1 1]
 [1 1]
 [1 1]]


**Empty**

In [40]:
print(np.empty([3,4]))

[[9.98953982e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.01855798e-312 3.80362944e+175 5.40152524e-038 1.10871645e-047]
 [6.69900993e+170 2.00343132e-052 1.94973687e+160 3.85777895e-057]]


## **Reshaping**

**1D to 3D**

In [60]:
# Original 1D array
array_1d = np.arange(24) 

# Reshape into 3D array with shape (2, 3, 4)
array_3d = array_1d.reshape((2, 3, 4))

print(array_3d)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


**2D to 3D**

In [98]:
import numpy as np

# Original 2D array
a = np.array([[1, 2, 3], [5, 6, 7], [8, 6, 5]])

# Reshape into a 3D array with shape (1, 3, 3)
a3d = a.reshape(1, 3, 3)

print(a3d)



[[[1 2 3]
  [5 6 7]
  [8 6 5]]]


**3D to 1D**

In [101]:
p,m,n = a3d.shape
total = m*n*p
print(a3d.reshape(total))

[1 2 3 5 6 7 8 6 5]


In [103]:
print(a3d.reshape(-1))

[1 2 3 5 6 7 8 6 5]


**3D to 2D**

In [106]:
a3d = np.array([[[1, 2, 3], 
                    [4, 5, 6]], 
                   
                   [[7, 8, 9], 
                    [10, 11, 12]]])

print("Original 3D array:")
print(a3d)

Original 3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [108]:
print(a3d.reshape(-1,1))
print(a3d.reshape(-1,1).ndim)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
2


In [110]:
d,m,n = a3d.shape
total = d*m,n
# Reshape the 3D array to 2D by combining the first two dimensions
print(a3d.reshape(total))
print(a3d.reshape(total).ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [112]:
d,m,n = a3d.shape
total = d,m*n
# Reshape the 3D array to 2D by combining the last two dimensions
print(a3d.reshape(total))
print(a3d.reshape(total).ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2


In [114]:
print(a3d.reshape(1,-1))
print(a3d.reshape(1,-1).ndim)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
2
