# Fancy_indexing

Fancy indexing in NumPy allows for selecting and manipulating data using arrays of indices. It is a powerful feature for advanced data manipulation and retrieval. 

### 1. **Basic Fancy Indexing**

Fancy indexing uses arrays of integer indices to access elements of another array. Each element in the index array represents a position in the original array.

#### Example:

In [19]:
import numpy as np

# Original array
arr = np.array([10, 20, 30, 40, 50])

# Indices to select
indices = np.array([1, 3, 4])

# Fancy indexing
selected_elements = arr[indices] 
print(selected_elements)

[10 20 30 40 50]
[1 3 4]
[20 40 50]



### 2. **Combined Fancy Indexing**

Fancy indexing can be combined with other indexing methods, such as boolean indexing or slicing, to perform more complex data retrieval and manipulation.


#### Example:

In [27]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Indices for rows and columns
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])

# Combined fancy indexing
selected_elements_combined = arr_2d[row_indices, col_indices] 
print(selected_elements_combined)

[2 9]


### 3. **Modified Fancy Indexing**

Modified fancy indexing involves using fancy indexing to alter specific elements of an array. This can be done by assigning new values to the selected indices.

#### Example:

In [37]:
# Original array
arr = np.array([10, 20, 30, 40, 50])

# Indices to modify
indices = np.array([1, 3])

# Modifying elements
arr[indices] = [100, 200] 
print(arr)
print(indices)
print(arr)

[ 10 100  30 200  50]
[1 3]
[ 10 100  30 200  50]



### 4. **Fancy Indexing with Multi-dimensional Arrays**

In multi-dimensional arrays, fancy indexing can be used to select and modify specific elements or sub-arrays. You can specify indices for each dimension separately.

#### Example:

In [35]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indices for rows and columns
rows = np.array([0, 1, 2])
cols = np.array([1, 0, 2])

# Combined fancy indexing
result = arr_2d[rows, cols]  

# Modifying elements
arr_2d[rows, cols] = [100, 200, 300]
print(result)

[2 4 9]


### 5. **Fancy Indexing with Boolean Arrays**

Fancy indexing can be combined with boolean arrays to select and modify elements that meet certain conditions.

#### Example:

In [ ]:
# Original array
arr = np.array([10, 20, 30, 40, 50])

# Boolean mask
mask = (arr > 20)

# Fancy indexing with boolean mask
selected_elements = arr[mask]  # Output: array([30, 40, 50])

# Modifying elements that meet the condition
arr[mask] = [300, 400, 500]

### 6. **Fancy Indexing with Different Shapes**

Fancy indexing can be applied to arrays of different shapes and dimensions, allowing for flexible data manipulation.

#### Example:

In [ ]:
# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Indices for different dimensions
dim0_indices = np.array([0, 1, 2])
dim1_indices = np.array([1, 0, 1])
dim2_indices = np.array([0, 1, 0])

# Combined fancy indexing
result = arr_3d[dim0_indices, dim1_indices, dim2_indices] 

- **Basic Fancy Indexing**: Select elements using arrays of indices.
- **Combined Fancy Indexing**: Combine fancy indexing with other indexing methods like boolean indexing.
- **Modified Fancy Indexing**: Use fancy indexing to modify specific elements.
- **Multi-dimensional Arrays**: Apply fancy indexing to select and modify elements in multi-dimensional arrays.
- **Fancy Indexing with Boolean Arrays**: Combine fancy indexing with boolean masks for conditional selection and modification.
- **Different Shapes**: Apply fancy indexing to arrays of different shapes and dimensions.

Fancy indexing provides powerful capabilities for advanced data manipulation and retrieval in NumPy. Understanding and effectively using these features can significantly enhance your data processing workflows.