# **Creating a NumPy ndarray Object**

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


*NumPy is used to work with arrays. The array object in NumPy is called ndarray*

**To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:**

In [94]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## **Dimensions in Array**

1D Array (1 dimension): <br>
This is a simple list of elements.
Example: [1, 2, 3, 4] <br>
It has one level of depth.<br><br>
2D Array (2 dimensions): <br>
This is an array of arrays, creating a table-like structure.
Example: [[1, 2], [3, 4], [5, 6]] <br>
It has two levels of depth. <br><br>
3D Array (3 dimensions):<br>
This is an array of 2D arrays.
Example: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] <br>
It has three levels of depth. <br><br>

Each time we add a set of square brackets, we're adding a dimension. <br> 


### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. <br> Each value in an array is a 0-D array.

In [104]:
import numpy as np

arr = np.array(42)

print(arr)

42


### 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [83]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # First element
print(arr.shape) #5 ELEMENTS
print(arr.ndim)

1
(5,)
1


### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array. <br>
These are often used to represent matrix or 2nd order tensors.
<br><br>
NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [79]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0, 1])
print(arr_2d.shape) #3ROWS AND 3 COLUMNS
print(arr_2d.ndim) 

2
(3, 3)
2


### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.
<br>
These are often used to represent a 3rd order tensor.

In [81]:
import numpy as np
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr_3d[0, 1, 1])
print(arr_3d.shape) # 3 "layers", each layer has 2 rows, and each row has 2 columns.
print(arr_3d.ndim)

4
(3, 2, 2)
3


### Higher Dimensional Arrays
An array can have any number of dimensions.
<br>
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [114]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
